Restuarant/Restuarant_web/Myapp/urls.py
from django.urls import path
from Myapp import views

urlpatterns = [

    path('',views.temp,name='index'),

    path('customers',views.savecustomer,name='customer'),

    path('updatecustomer/<str:pk>',views.updatecustomer,name='updatecustomer'),

    path('deletecustomer/<str:pk>',views.deletecustomer,name='deletecustomer'),
]

Restuarant/Restuarant_web/Restuarant_web/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('Myapp.urls')), 
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Restuarant/Restuarant_web/Myapp/models.py
from django.db import models
from datetime import datetime

from django.db.models.fields.related import ForeignKey  
# Create your models here.

class Login(models.Model):
   Username  = models.CharField(max_length=30,unique=True)
   password  = models.CharField(max_length=30,unique=True)
   Email     = models.CharField(max_length=50)
   EntryDate = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class LoginDetail(models.Model):
	LoginID   = models.ForeignKey(Login, on_delete=models.CASCADE)
	Username  = models.CharField(max_length=30)
	Email     = models.CharField(max_length=50)
	LoginTime = models.DateTimeField(auto_now=True)

class DistributerPersonalDetail(models.Model):
	FirstName     = models.CharField(max_length=30)
	LastName      = models.CharField(max_length=30)
	FatherName    = models.CharField(max_length=30)
	CNIC          = models.CharField(max_length=13,unique=True,blank=True)
	Age           = models.IntegerField()
	Gender        = models.CharField(max_length=8)
	MaritalStatus = models.CharField(max_length=10)
	EntryDate     = models.DateTimeField(auto_now=True)

class DistributerContactDetail(models.Model):
   DistributerPID = models.ForeignKey(DistributerPersonalDetail,on_delete=models.CASCADE)
   Address        = models.CharField(max_length=100)
   City           = models.CharField(max_length=100)
   Country        = models.CharField(max_length=100)
   PhoneNo        = models.CharField(max_length=13)
   LandLineNo     = models.CharField(max_length=15,blank=True)
   Email          = models.CharField(max_length=50,blank=True)
   Others         = models.CharField(max_length=100,blank=True)
   EntryDate      = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class DistributerBrandDetail(models.Model):
   DistributerPID = models.ForeignKey(DistributerPersonalDetail, on_delete=models.CASCADE)
   BrandName      = models.CharField(max_length=30,unique=True)
   Address        = models.CharField(max_length=100)
   Email          = models.CharField(max_length=50,unique=True,blank=True)
   PhoneNo        = models.CharField(max_length=13,unique=True)
   EntryDate      = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class Ingredient(models.Model):
   IngredientName  = models.CharField(max_length=30,unique=True)
   IngredientPrice = models.DecimalField(max_digits=8, decimal_places=2)
   Size            = models.CharField(max_length=10,blank=True)
   Description     = models.CharField(max_length=100,blank=True)
   EntryDate       = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class ProductPurchase(models.Model):
   BrandID       = models.ForeignKey(DistributerBrandDetail, on_delete=models.CASCADE)
   IngredientID  = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
   PurchasePrice = models.DecimalField(max_digits=8, decimal_places=2)
   Quantity      = models.IntegerField() 
   Size          = models.CharField(max_length=10,blank=True)
   PurchaseDate  = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class DistributerPayment(models.Model):
   DistributerPID = models.ForeignKey(DistributerPersonalDetail, on_delete=models.CASCADE)
   PurchaseID     = models.ForeignKey(ProductPurchase, on_delete=models.CASCADE)
   PaidAmount     = models.DecimalField(max_digits=8, decimal_places=2)
   RemaningAmount = models.DecimalField(max_digits=8, decimal_places=2) 
   PaymentMethod  = models.CharField(max_length=50)
   PaymentType    = models.CharField(max_length=13)
   EntryDate      = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class CurrentStock(models.Model):
   IngredientID = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
   Quantity     = models.IntegerField()
   EntryDate    = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class Food(models.Model):
   FoodImage       = models.ImageField(upload_to="images/")
   FoodName        = models.CharField(max_length=30,unique=True)
   FoodType        = models.CharField(max_length=50)
   FoodDescription = models.CharField(max_length=100,blank=True)
   EntryDate       = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class FoodSize(models.Model):
   FoodID    = models.ForeignKey(Food, on_delete=models.CASCADE)
   FoodSize  = models.CharField(max_length=10)
   FoodPrice = models.DecimalField(max_digits=8, decimal_places=2) 
   EntryDate = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class FoodIngredient(models.Model):
   FoodID       = models.ForeignKey(Food, on_delete=models.CASCADE)
   FoodSizeID   = models.ForeignKey(FoodSize, on_delete=models.CASCADE)
   IngredientID = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
   Quantity     = models.IntegerField()
   Size         = models.CharField(max_length=10)
   EntryDate    = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class Offers(models.Model):
   OfferName    = models.CharField(max_length=30,unique=True)
   OfferPrice   = models.DecimalField(max_digits=8, decimal_places=2) 
   Availability = models.CharField(max_length=10,blank=True)
   CreateTime   = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class OffersFood(models.Model):
   OfferID    = models.ForeignKey(Offers, on_delete=models.CASCADE)
   FoodID     = models.ForeignKey(Food, on_delete=models.CASCADE)
   FoodSizeID = models.ForeignKey(FoodSize, on_delete=models.CASCADE)
   Quantity   = models.IntegerField() 
   EntryDate  = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class EmployeePesonalDetail(models.Model):
   FirstName     = models.CharField(max_length=30)
   LastName      = models.CharField(max_length=30,blank=True)
   CNIC          = models.CharField(max_length=13,unique=True,blank=True)
   FatherName    = models.CharField(max_length=30)
   Age           = models.IntegerField()
   Gender        = models.CharField(max_length=8)
   MaritalStatus = models.CharField(max_length=10)
   EntryDate     = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class Employee(models.Model):
   EmployeePID       = models.ForeignKey(EmployeePesonalDetail, on_delete=models.CASCADE)
   JobName           = models.CharField(max_length=30)
   EmployeementYears = models.IntegerField()
   Salary            = models.DecimalField(max_digits=8, decimal_places=2) 
   Bonus             = models.DecimalField(max_digits=8, decimal_places=2) 
   DutyStartTime     = models.TimeField(blank=True)
   DutyEndTime       = models.TimeField(blank=True)
   JobDescription    = models.CharField(max_length=100)
   EntryDate         = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class Customer(models.Model):
   FirstName = models.CharField(max_length=30)
   LastName  = models.CharField(max_length=30,blank=True)
   CNIC      = models.CharField(max_length=13,blank=True)
   PhoneNo1  = models.CharField(max_length=13,blank=True)
   Email     = models.CharField(max_length=50,blank=True)
   Address   = models.CharField(max_length=100,blank=True)
   EntryDate = models.DateTimeField(default=datetime.now(), blank=True)
   def __str__(self):
      return str(self.id)

class CustomerOrderBooking(models.Model):
   CustomerID  = models.ForeignKey(Customer, on_delete=models.CASCADE)
   EmployeePID = models.ForeignKey(EmployeePesonalDetail, on_delete=models.CASCADE) 
   TotalBill   = models.DecimalField(max_digits=8, decimal_places=2) 
   EntryDate   = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class CustomerOrderDetail(models.Model): 
   CustomerOrderID = models.ForeignKey(CustomerOrderBooking, on_delete=models.CASCADE) 
   ProductName     = models.CharField(max_length=30)
   ProductSize     = models.CharField(max_length=10)
   ProductQuantity = models.IntegerField()
   SalePrice       = models.DecimalField(max_digits=8, decimal_places=2) 
   EntryDate       = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class EmployeeContactDetail(models.Model):
   EmployeePID = models.ForeignKey(EmployeePesonalDetail, on_delete=models.CASCADE)
   Address1    = models.CharField(max_length=100)
   City        = models.CharField(max_length=100) 
   Country     = models.CharField(max_length=100)
   PhoneNo1    = models.CharField(max_length=13,unique=True)
   LandLineNo  = models.CharField(max_length=15,blank=True)
   Email       = models.CharField(max_length=50,blank=True)
   EntryDate   = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class Qualification(models.Model):
   EmployeePID   = models.ForeignKey(EmployeePesonalDetail, on_delete=models.CASCADE)
   DegreeName    = models.CharField(max_length=50)
   InstituteName = models.CharField(max_length=50)
   PassingYear   = models.CharField(max_length=10,blank=True)
   ObtainedMarks = models.IntegerField()
   TotalMarks    = models.IntegerField()
   Grade         = models.CharField(max_length=2,blank=True)
   Other         = models.CharField(max_length=100,blank=True)
   EntryDate     = models.DateTimeField(auto_now=True)
   def __str__(self):
      return str(self.id)

class EmployeeSkill(models.Model):
   EmployeePID         = models.ForeignKey(EmployeePesonalDetail, on_delete=models.CASCADE)
   SkillName           = models.CharField(max_length=50)
   OrganizationName    = models.CharField(max_length=50)
   CertificationNumber = models.CharField(max_length=50,blank=True)
   LearnStartDate      = models.DateField()
   LearnEndDate        = models.DateField()
   Others              = models.CharField(max_length=100,blank=True)
   EntryDate           = models.DateTimeField(auto_now=True)
   def __str__(self):

Restuarant/Restuarant_web/Myapp/forms.py
from django.db.models import fields
from .models import *
from django import forms

class cusform(forms.ModelForm):
    class Meta:
        model = Customer
        fields='__all__'

Restuarant/Restuarant_web/Myapp/views.py
from django import forms
from django.shortcuts import redirect, render
from .forms import *
from .models import *
# Create your views here.

def temp(request):
    offerset = Offers.objects.all()
    dataset = Customer.objects.all()
    foodset = Food.objects.all()
    return render(request,'Myapp/index.html',{'dat':dataset,'offers':offerset,'product':foodset})

def savecustomer(request):
    form = cusform()
    if request.method == 'POST':
        form = cusform(request.POST)
        if form.is_valid:
            form.save()
            return redirect('/customers')
    context ={'form':form}
    return render(request,'Myapp/Customerform.html',context)

def updatecustomer(request,pk):
    form1= Customer.objects.get(id=pk)
    form=cusform(instance=form1)
    if request.method == 'POST':
        form = cusform(request.POST,instance=form1)
        if form.is_valid:
            form.save()
           # return redirect('/customers')
    context ={'form':form1}
    return render(request,'Myapp/updatecustomer.html',context)

def deletecustomer(request,pk):
    form1= Customer.objects.get(id=pk)
    form1.delete()
    return redirect('index')

Restuarant/Restuarant_web/Myapp/templates/Myapp/Customerform.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Royal Kitchen</title>

	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="">
	<meta name="description" content="">
<!--

Template 2076 Royal Kitchen

http://www.tooplate.com/view/2076-Royal Kitchen

-->
	<link rel="stylesheet" href="{% static 'Myapp/css/bootstrap.min.css'%}">
	<link rel="stylesheet" href="{% static 'Myapp/css/animate.min.css'%}">
	<link rel="stylesheet" href="{% static 'Myapp/css/font-awesome.min.css'%}">
	<link rel="stylesheet" href="{% static 'Myapp/css/nivo-lightbox.css'%}">
	<link rel="stylesheet" href="{% static 'Myapp/css/nivo_themes/default/default.css'%}">
	<link rel="stylesheet" href="{% static 'Myapp/css/style.css'%}">
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,500' rel='stylesheet' type='text/css'>
</head>
<body>

<!-- navigation section -->
<section class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
			</button>
			<a href="#" class="navbar-brand">Royal Kitchen</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="{% url 'index'%}" class="smoothScroll">HOME</a></li>
			</ul>
		</div>
	</div>
</section>
<br>
<br>
<br>

<section id="InputCustomer" class="parallax-section">
	<div class="container">
		<div class="row">
			<div class="col-md-offset-1 col-md-10 col-sm-12 text-center">
				
				<h1 class="heading">Save Customer Information</h1>
				<hr>
			</div>
			<div class="col-md-offset-1 col-md-10 col-sm-12 wow fadeIn" data-wow-delay="0.7s">

				<form action="" method="post">

					{% csrf_token %}
					<div class="col-md-6 col-sm-6" style="margin-top: 1%;">
						<input name="FirstName" type="text" class="form-control" id="id_FirstName" placeholder="FirstName">
				  </div>
					<div class="col-md-6 col-sm-6" style="margin-top: 1%;">
						<input name="LastName" type="text" class="form-control" id="id_LastName" placeholder="LastName">
					</div>		  

				  <div class="col-md-12 col-sm-12" style="margin-top: 1%;">
					<input name="CNIC" type="text" class="form-control" id="id_CNIC" placeholder="CNIC">
			  </div>
			  
		  <div class="col-md-6 col-sm-6" style="margin-top: 1%;">
			<input name="Email" type="text" class="form-control" id="id_Email" placeholder="Email">
	  </div>
		<div class="col-md-6 col-sm-6" style="margin-top: 1%;">
			<input name="Address" type="text" class="form-control" id="id_Address" placeholder="Address">
							</div>

							<div class="col-md-12 col-sm-12" style="margin-top: 1%;">
								<input name="PhoneNo1" type="text" class="form-control" id="id_PhoneNo1" placeholder="Phone No">
						  </div>
		
					</div>
					<div class="col-md-2 col-sm-2" style="margin-top: 2%; margin-bottom: 2%; margin-left: 9.5%;">
						<input name="Save" type="submit" class="form-control" value="Save">
					</div>
					
				</form>
			</div>
			
	</div>
</section>
</body>

<!-- JAVASCRIPT JS FILES -->	
<script src="{% static 'Myapp/js/jquery.js'%}"></script>
<script src="{% static 'Myapp/js/bootstrap.min.js'%}"></script>
<script src="{% static 'Myapp/js/jquery.parallax.js'%}"></script>
<script src="{% static 'Myapp/js/smoothscroll.js'%}"></script>
<script src="{% static 'Myapp/js/nivo-lightbox.min.js'%}"></script>
<script src="{% static 'Myapp/js/wow.min.js'%}"></script>
<script src="{% static 'Myapp/js/custom.js'%}"></script>

</body>
</html>

Restuarant/Restuarant_web/Myapp/templates/Myapp/updatecustomer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    
<head>
	<meta charset="utf-8">
	<title>Royal Kitchen</title>

	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="">
	<meta name="description" content="">
<!--

Template 2076 Royal Kitchen

http://www.tooplate.com/view/2076-Royal Kitchen

-->
	<link rel="stylesheet" href="{% static 'Myapp/css/bootstrap.min.css'%}">
	<link rel="stylesheet" href="{% static 'Myapp/css/animate.min.css'%}">
	<link rel="stylesheet" href="{% static 'Myapp/css/font-awesome.min.css'%}">
	<link rel="stylesheet" href="{% static 'Myapp/css/nivo-lightbox.css'%}">
	<link rel="stylesheet" href="{% static 'Myapp/css/nivo_themes/default/default.css'%}">
	<link rel="stylesheet" href="{% static 'Myapp/css/style.css'%}">
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,500' rel='stylesheet' type='text/css'>
</head>
<body>

<!-- navigation section -->
<section class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
			</button>
			<a href="#" class="navbar-brand">Royal Kitchen</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="{% url 'index'%}" class="smoothScroll">HOME</a></li>
			</ul>
		</div>
	</div>
</section>
<br>
<br>
<br>

<section id="InputCustomer" class="parallax-section">
	<div class="container">
		<div class="row">
			<div class="col-md-offset-1 col-md-10 col-sm-12 text-center">
				
				<h1 class="heading">Update Customer Information</h1>
				<hr>
			</div>
			<div class="col-md-offset-1 col-md-10 col-sm-12 wow fadeIn" data-wow-delay="0.7s">

				<form action="" method="POST">

					{% csrf_token %}
					<div class="col-md-6 col-sm-6" style="margin-top: 1%;">
						<input name="FirstName" type="text" class="form-control" id="id_FirstName" value={{form.FirstName}} placeholder="FirstName">
				  </div>
					<div class="col-md-6 col-sm-6" style="margin-top: 1%;">
						<input name="LastName" type="text" class="form-control" id="id_LastName" value={{form.LastName}} placeholder="LastName">
					</div>		  

				  <div class="col-md-12 col-sm-12" style="margin-top: 1%;">
					<input name="CNIC" type="text" class="form-control" id="id_CNIC" value={{form.CNIC}} placeholder="CNIC">
			  </div>
			  
		  <div class="col-md-6 col-sm-6" style="margin-top: 1%;">
			<input name="Email" type="text" class="form-control" id="id_Email" value={{form.Email}} placeholder="Email">
	  </div>
		<div class="col-md-6 col-sm-6" style="margin-top: 1%;">
			<input name="Address" type="text" class="form-control" id="id_Address" value={{form.Address}} placeholder="Address">
							</div>

							<div class="col-md-12 col-sm-12" style="margin-top: 1%;">
								<input name="PhoneNo1" type="text" class="form-control" id="id_PhoneNo1" value={{form.PhoneNo1}} placeholder="Phone No">
						  </div>
		
					</div>
					<div class="col-md-2 col-sm-2" style="margin-top: 2%; margin-bottom: 2%; margin-left: 9.5%;">
						<input name="Save" type="submit" class="form-control" value="Save">
					</div>
					
				</form>
			</div>
			
	</div>
</section>
</body>

<!-- JAVASCRIPT JS FILES -->	
<script src="{% static 'Myapp/js/jquery.js'%}"></script>
<script src="{% static 'Myapp/js/bootstrap.min.js'%}"></script>
<script src="{% static 'Myapp/js/jquery.parallax.js'%}"></script>
<script src="{% static 'Myapp/js/smoothscroll.js'%}"></script>
<script src="{% static 'Myapp/js/nivo-lightbox.min.js'%}"></script>
<script src="{% static 'Myapp/js/wow.min.js'%}"></script>
<script src="{% static 'Myapp/js/custom.js'%}"></script>

</body>
</html>